### ISSUE TITLE
Can't init PostgreSQL

### ISSUE THREAD

**Issue by mmaya** [mmaya/aws-gdk#2]
Installation was not succeeded because couldn't init Postegree

`make: /usr/lib/postgresql/9.5/bin/initdb: Command not found Makefile:161: recipe for target 'postgresql/data' failed make: *** [postgresql/data] Error 127
![image](https://cloud.githubusercontent.com/assets/25435595/22478386/c3c137f2-e7d0-11e6-9261-32901c4f5f5d.png)
`

**Comment by mmaya** [comment]
Postgres is installed

` pg_config --version
PostgreSQL 9.5.5`

But there's no Postgresql directory on usr/lib

**Comment by mmaya** [comment]
PostgreSQL wasn't installed. I installed and found the init command where should be.
'sudo apt-get install postgresql'

I'll terminate and relaunch AMI and test GDK from the scratch.

**Comment by mmaya** [comment]
Still doesn't init, but it's showing another error.

**Comment by mmaya** [comment]
I'm not using a root user, but the GDK was terminated with the message;
`initdb: cannot be run as root
Please log in (using, e.g., "su") as the (unprivileged) user that will
own the server process.`

**Comment by mmaya** [comment]
I tried to start Postgres before run GDK install

/usr/lib/postgresql/9.5/bin/initdb --locale=C -E utf-8 postgresql/data
initdb

Success. You can now start the database server using:

    /usr/lib/postgresql/9.5/bin/pg_ctl -D postgresql/data -l logfile start

Run GDK and got another error that will be resolve in an issue.
/usr/bin/rake:27:in `<main>'
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "database"=>"gitlabhq_test", "pool"=>5, "host"=>"/home/ubuntu/gitlab-development-kit/postgresql"}
-- enable_extension("plpgsql")
rake aborted!
PG::ConnectionBad: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/home/ubuntu/gitlab-development-kit/postgresql/.s.PGSQL.5432"?
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `initialize'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `new'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `connect'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `postgresql_connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_handling.rb:87:in `connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:648:in `connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:664:in `block in method_missing'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:634:in `block in say_with_time'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:634:in `say_with_time'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:654:in `method_missing'
/home/ubuntu/gitlab-development-kit/gitlab/db/schema.rb:17:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/schema.rb:41:in `instance_eval'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/schema.rb:41:in `define'/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/schema.rb:61:in `define'/home/ubuntu/gitlab-development-kit/gitlab/db/schema.rb:14:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/var/lib/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
/var/lib/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:219:in `load_schema_for'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:236:in `block in load_schema_current'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:276:in `block in each_current_configuration'/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:275:in `each'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:275:in `each_current_configuration'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:235:in `load_schema_current'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:247:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:251:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:142:in `block (2 levels) in <top (required)>'
/home/ubuntu/gitlab-development-kit/gitlab/lib/tasks/gitlab/setup.rake:17:in `setup_db'
/home/ubuntu/gitlab-development-kit/gitlab/lib/tasks/gitlab/setup.rake:4:in `block (2 levels) in <top (required)>'
/home/ubuntu/gitlab-development-kit/gitlab/lib/tasks/dev.rake:7:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:schema:load
(See full trace by running task with --trace)
support/bootstrap-rails failed
Makefile:161: recipe for target 'postgresql/data' failed
make: *** [postgresql/data] Error
