### ISSUE TITLE
Can't connect to the database

### ISSUE THREAD

**Issue by mmaya** [mmaya/aws-gdk#4]
GDK install can't connect to the database, although service is up. Error message:

`/usr/bin/rake:27:in `<main>'
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "database"=>"gitlabhq_test", "pool"=>5, "host"=>"/home/ubuntu/gitlab-development-kit/postgresql"}
-- enable_extension("plpgsql")
rake aborted!
PG::ConnectionBad: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/home/ubuntu/gitlab-development-kit/postgresql/.s.PGSQL.5432"?
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `initialize'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `new'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `connect'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `postgresql_connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_handling.rb:87:in `connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:648:in `connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:664:in `block in method_missing'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:634:in `block in say_with_time'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:634:in `say_with_time'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:654:in `method_missing'
/home/ubuntu/gitlab-development-kit/gitlab/db/schema.rb:17:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/schema.rb:41:in `instance_eval'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/schema.rb:41:in `define'/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/schema.rb:61:in `define'/home/ubuntu/gitlab-development-kit/gitlab/db/schema.rb:14:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/var/lib/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
/var/lib/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:219:in `load_schema_for'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:236:in `block in load_schema_current'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:276:in `block in each_current_configuration'/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:275:in `each'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:275:in `each_current_configuration'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:235:in `load_schema_current'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:247:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:251:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:142:in `block (2 levels) in <top (required)>'
/home/ubuntu/gitlab-development-kit/gitlab/lib/tasks/gitlab/setup.rake:17:in `setup_db'
/home/ubuntu/gitlab-development-kit/gitlab/lib/tasks/gitlab/setup.rake:4:in `block (2 levels) in <top (required)>'
/home/ubuntu/gitlab-development-kit/gitlab/lib/tasks/dev.rake:7:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:schema:load
(See full trace by running task with --trace)
support/bootstrap-rails failed
Makefile:161: recipe for target 'postgresql/data' failed
make: *** [postgresql/data] Error 1`

**Comment by mmaya** [comment]
/usr/bin/rake:27:in `<main>'
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "database"=>"gitlabhq_test", "pool"=>5, "host"=>"/home/ubuntu/gitlab-development-kit/postgresql"}
-- enable_extension("plpgsql")
rake aborted!
PG::ConnectionBad: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/home/ubuntu/gitlab-development-kit/postgresql/.s.PGSQL.5432"?
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `initialize'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `new'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `connect'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `postgresql_connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_handling.rb:87:in `connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:648:in `connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:664:in `block in method_missing'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:634:in `block in say_with_time'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:634:in `say_with_time'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:654:in `method_missing'
/home/ubuntu/gitlab-development-kit/gitlab/db/schema.rb:17:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/schema.rb:41:in `instance_eval'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/schema.rb:41:in `define'/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/schema.rb:61:in `define'/home/ubuntu/gitlab-development-kit/gitlab/db/schema.rb:14:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/var/lib/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
/var/lib/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:219:in `load_schema_for'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:236:in `block in load_schema_current'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:276:in `block in each_current_configuration'/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:275:in `each'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:275:in `each_current_configuration'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:235:in `load_schema_current'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:247:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:251:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:142:in `block (2 levels) in <top (required)>'
/home/ubuntu/gitlab-development-kit/gitlab/lib/tasks/gitlab/setup.rake:17:in `setup_db'
/home/ubuntu/gitlab-development-kit/gitlab/lib/tasks/gitlab/setup.rake:4:in `block (2 levels) in <top (required)>'
/home/ubuntu/gitlab-development-kit/gitlab/lib/tasks/dev.rake:7:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:schema:load
(See full trace by running task with --trace)
support/bootstrap-rails failed
Makefile:161: recipe for target 'postgresql/data' failed
make: *** [postgresql/data] Error 1

**Comment by mmaya** [comment]
buntu@ip-172-31-27-48:~/gitlab-development-kit$ gdk run db
(in /home/ubuntu/gitlab-development-kit)
14:09:31 redis.1                 | started with pid 16828
14:09:31 postgresql.1            | started with pid 16829
14:09:31 redis.1                 | sh: 1: exec: redis-server: not found
14:09:31 postgresql.1            | LOG:  database system was shut down at 2017-02-02 10:35:37 UTC
14:09:31 postgresql.1            | LOG:  MultiXact member wraparound protections are now enabled
14:09:31 postgresql.1            | LOG:  database system is ready to accept connections
14:09:31 postgresql.1            | LOG:  autovacuum launcher started
14:09:31 redis.1                 | exited with code 127
14:09:31 system                  | sending SIGTERM to all processes
14:09:31 postgresql.1            | LOG:  received fast shutdown request
14:09:31 postgresql.1            | LOG:  aborting any active transactions
14:09:31 postgresql.1            | LOG:  autovacuum launcher shutting down
14:09:31 postgresql.1            | LOG:  shutting down
14:09:31 postgresql.1            | LOG:  database system is shut down
14:09:31 postgresql.1            | Sending INT to 16832
ubuntu@ip-172-31-27-48:~/gitlab-development-kit$ de 0

**Comment by mmaya** [comment]
`buntu@ip-172-31-27-48:~/gitlab-development-kit$ gdk run db
(in /home/ubuntu/gitlab-development-kit)
14:09:31 redis.1                 | started with pid 16828
14:09:31 postgresql.1            | started with pid 16829
14:09:31 redis.1                 | sh: 1: exec: redis-server: not found
14:09:31 postgresql.1            | LOG:  database system was shut down at 2017-02-02 10:35:37 UTC
14:09:31 postgresql.1            | LOG:  MultiXact member wraparound protections are now enabled
14:09:31 postgresql.1            | LOG:  database system is ready to accept connections
14:09:31 postgresql.1            | LOG:  autovacuum launcher started
14:09:31 redis.1                 | exited with code 127
14:09:31 system                  | sending SIGTERM to all processes
14:09:31 postgresql.1            | LOG:  received fast shutdown request
14:09:31 postgresql.1            | LOG:  aborting any active transactions
14:09:31 postgresql.1            | LOG:  autovacuum launcher shutting down
14:09:31 postgresql.1            | LOG:  shutting down
14:09:31 postgresql.1            | LOG:  database system is shut down
14:09:31 postgresql.1            | Sending INT to 16832
ubuntu@ip-172-31-27-48:~/gitlab-development-kit$ de 0
`

**Comment by mmaya** [comment]
`Make sure Postgres is running otherwise db:migrate will fail
------------------------------------------------------------

cd /home/ubuntu/gitlab-development-kit/gitlab && \
        bundle exec rake db:migrate db:test:prepare && \
        npm prune && \
        npm install
rake aborted!
PG::ConnectionBad: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/home/ubuntu/gitlab-development-kit/postgresql/.s.PGSQL.5432"?
`

**Comment by mmaya** [comment]
etstat -nlp | grep 5432
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      -               
unix  2      [ ACC ]     STREAM     LISTENING     125835   -                   /var/run/postgresql/.s.PGSQL.5432

**Comment by mmaya** [comment]
netstat -nlp | grep 5432
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      -               
unix  2      [ ACC ]     STREAM     LISTENING     46276    -                   /var/run/postgresql/.s.PGSQL.5432

netstat -lp --protocol=unix | grep postgres
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
unix  2      [ ACC ]     STREAM     LISTENING     46276    -                   /var/run/postgresql/.s.PGSQL.5432

**Comment by mmaya** [comment]
ln -s /home/ubuntu/gitlab-development-kit/postgresql/.s.PGSQL.5432 /var/run/postgresql/.s.PGSQL.5432

**Comment by mmaya** [comment]
sudo pg_createcluster --socketdir=/home/ubuntu/gitlab-development-kit/postgresql/.s.PGSQL.5432

**Comment by mmaya** [comment]
Creating new cluster 9.5/main ...
  config /etc/postgresql/9.5/main
  data   /var/lib/postgresql/9.5/main
  locale en_US.UTF-8
  socket /var/run/postgresql
  port   5432

**Comment by mmaya** [comment]
PG::ConnectionBad: FATAL:  Peer authentication failed for user "gitlab"

**Comment by mmaya** [comment]
Edited database.yml with the correct unix socket and worked
